name: Build and Push Frontend Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          cd frontend
          docker build -f Dockerfile.advancedv2 -t ghcr.io/mathieu-junia/frontend:${{ github.sha }} -t ghcr.io/mathieu-junia/frontend:latest .

      - name: Install and run Container Structure Tests
        run: |
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/latest/download/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          mkdir -p $HOME/bin
          export PATH=$PATH:$HOME/bin
          mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
          cd frontend
          container-structure-test test --image ghcr.io/mathieu-junia/frontend:${{ github.sha }} --config tests/cst-advancedv2.yaml

      - name: Log in to the registry
        run: docker login ghcr.io -u ${{ secrets.GITHUB_TOKEN }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: |
          docker push ghcr.io/mathieu-junia/frontend:${{ github.sha }}
          docker push ghcr.io/mathieu-junia/frontend:latest
